// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3FAAI1g_gVfAQoYGvhs3d6xczJurc9A',
    appId: '1:978793568422:web:f63c56ff4afbfd2abbbc67',
    messagingSenderId: '978793568422',
    projectId: 'takative-todo-app',
    authDomain: 'takative-todo-app.firebaseapp.com',
    databaseURL: 'https://takative-todo-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takative-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjGAQZm1XlkQyVyng2C9ZXZCQ9QbdWII',
    appId: '1:978793568422:android:40694af90025e4cabbbc67',
    messagingSenderId: '978793568422',
    projectId: 'takative-todo-app',
    databaseURL: 'https://takative-todo-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takative-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOL6yOBXmH8JZUai08YrG3PlU-jjXgIQ',
    appId: '1:978793568422:ios:5227ab4ba52e09d2bbbc67',
    messagingSenderId: '978793568422',
    projectId: 'takative-todo-app',
    databaseURL: 'https://takative-todo-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takative-todo-app.firebasestorage.app',
    iosClientId: '978793568422-rqvgoc5mdhepdocc5lukras40gikue3b.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.talkativeTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOL6yOBXmH8JZUai08YrG3PlU-jjXgIQ',
    appId: '1:978793568422:ios:5227ab4ba52e09d2bbbc67',
    messagingSenderId: '978793568422',
    projectId: 'takative-todo-app',
    databaseURL: 'https://takative-todo-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takative-todo-app.firebasestorage.app',
    iosClientId: '978793568422-rqvgoc5mdhepdocc5lukras40gikue3b.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.talkativeTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk3FAAI1g_gVfAQoYGvhs3d6xczJurc9A',
    appId: '1:978793568422:web:a0c2a1784d42f0c4bbbc67',
    messagingSenderId: '978793568422',
    projectId: 'takative-todo-app',
    authDomain: 'takative-todo-app.firebaseapp.com',
    databaseURL: 'https://takative-todo-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takative-todo-app.firebasestorage.app',
  );
}
